version: '3.8'
services:
  udigital:
    container_name: udigital-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
      - cronlogs:/cron
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

volumes:
  logs:
    external: false
  cronlogs:
    external: false