version: '3.8'
services:
  backend:
    container_name: udigital
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

volumes:
  logs:
    external: false